[build-system]
requires = ["poetry-core>=2.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[project]
name = "my_sqlalchemy"
description = "A simplified SQLAlchemy wrapper with built-in model validation and database management utilities"
license = "LICENSE"
readme = "README.md"
keywords = ["sqlalchemy", "database", "orm", "sql", "sqlite", "postgresql", "mysql"]
authors = [
        { name = "Fernando Casale Neto", email = "fcasalen@gmail.com" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable"
]
requires-python = ">=3.11, <4.0"
dynamic = ["version", "dependencies"]

[project.scripts]
my_sqlalchemy_manager = "my_sqlalchemy.manager:cli"

[project.urls]
Homepage = "https://github.com/fcasalen/my_sqlalchemy"
Repository = "https://github.com/fcasalen/my_sqlalchemy.git"
Issues = "https://github.com/fcasalen/my_sqlalchemy/issues"

[tool.poetry]
packages = [{include = "my_sqlalchemy", from = "src"}]
version = "0.0.0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "{base}"

[tool.poetry.dependencies]
sqlalchemy = ">=2.0.36"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"
detect-secrets = "^1.5.0"
pytest-cov = "^7.0.0"
pre-commit = "^4.5.1"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]

[tool.ruff.lint]
select = ["I", "F", "E", "W", "C", "N"]

[tool.ruff.format]
docstring-code-format = true
